### ISSUE TITLE
Invalid bounds

### ISSUE THREAD

**Issue by phadej** [OpenSourceOrg/haskell-opensource#7]
I made a revision to correct build on GHC-7.8:
https://hackage.haskell.org/package/opensource-0.1.0.0/revisions/

```
Flags chosen: transformers_compat=False
Dependency aeson ==0.11.2.0: using aeson-0.11.2.0
Dependency base ==4.7.0.2: using base-4.7.0.2
Dependency http-client ==0.4.29: using http-client-0.4.29
Dependency http-client-tls ==0.2.4.1: using http-client-tls-0.2.4.1
Dependency text ==1.2.2.1: using text-1.2.2.1
Dependency transformers ==0.3.0.0: using transformers-0.3.0.0
```

Note: `> 0.3` means solver is free to pick `0.3.1` for example. I'd rather use closed lower bound, for example`>=0.4`.

**Comment by phadej** [comment]
Also with https://github.com/hvr/multi-ghc-travis it's easy to setup travis CI, which would catch those in advance!

**Comment by clinty** [comment]
Oops, that was supposed to have been >= 0.3

**Comment by clinty** [comment]
https://github.com/OpenSourceOrg/haskell-opensource/commit/fe7f4129a11a73801115f7d527e9ed3ab36186a4

**Comment by phadej** [comment]
`>= 0.3` is not enough. http://hackage.haskell.org/package/transformers-0.3.0.0 doesn't have `Except` module.

_EDIT_ `0.3.0.0 > 0.3`, this is a bit nasty corner case.

**Comment by clinty** [comment]
I'm confused; isn't that the point of transformers-compat?

**Comment by phadej** [comment]
@clinty
you have two branches:
- `transformers, transformers-compat >= 0.3`, that branch is ok
- `transformers >= 0.3` (no `transformers-compat`), which fails.

One option would be to have (also with upper bounds as [PVP](https://wiki.haskell.org/Package_versioning_policy) says)

```
if flag(transformers_compat)
  build-depends:
      transformers             >= 0.2 && <0.4
    , transformers-compat      >= 0.3 && <0.6
else
  build-depends:
      transformers             >= 0.4 && <0.6
```

Yet much simpler option would be to have just without flags. Then `Control.Monad.Trans.Except` might be in either package, but as package author you don't need to care.

```
build-depends:
    transformers             >= 0.2 && <0.6
  , transformers-compat      >= 0.3 && <0.6
```

**Comment by clinty** [comment]
In Debian we would need to patch transformers-compat out, so the former solution is more convenient.

**Comment by phadej** [comment]
I see.
